// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clpbnwbjojobhhfbeytb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscGJud2Jqb2pvYmhoZmJleXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTA0ODUsImV4cCI6MjA2MDU2NjQ4NX0.qy4SC6m2L9QThWnyroSdBDldPz01Kf-OSTE5uqwMRtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);